server:
  port: 9000

spring:
  application:
    name: demo
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    platform: mysql
    url:
    username: admin
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
